server:
  port: 18182
  port1: 18180
  port2: 18181
  port3: 18182

eureka:
  instance:
    hostname: HJNAPP03
    hostname1: HJNAPP01
    hostname2: HJNAPP02
    hostname3: HJNAPP04
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname1}:${server.port1}/eureka/,http://${eureka.instance.hostname2}:${server.port2}/eureka/,http://${eureka.instance.hostname3}:${server.port3}/eureka/

spring:
  application:
    name: hjntest